import { Web3Button } from "@web3modal/react";
import Head from "next/head";
import styles from "./Home.module.css";
import { useAccount } from "wagmi";
import dynamic from "next/dynamic";
import { init, useLazyQuery } from "@airstack/airstack-react";
import { useEffect, useState } from "react";
init("ddfcc652b902475e99ee40f6db959ff9");

const ConnectNft = dynamic(() => import("@/components/ConnectNFT/ConnectNft"), {
    ssr: false,
});
const Pooltogether = dynamic(
    () => import("@/components/PoolTogether/PoolTogether"),
    { ssr: false }
);

const Home = () => {
    const [NFTs, setNFTs] = useState([]);

    const account = useAccount({
        onConnect({ address, connector, isReconnected }) {
            console.log("Connected", { address, connector, isReconnected });
        },
    });

    const getNFTs = `{
    TokenBalances(
      input: {filter: {owner: {_eq: "${account.address}"}, tokenType: {_eq: ERC721}}, blockchain: polygon, limit: 50}
    ) {
      TokenBalance {
        tokenAddress
        amount
        formattedAmount
        tokenType
        owner {
          addresses
        }
        tokenNfts {
          address
          tokenId
          blockchain
          contentValue {
            image {
              original
            }
          }
        }
      }
    }
  }  
  `;

    const [fetch_NFTs, NFTs_queryResponse] = useLazyQuery(getNFTs);

    useEffect(() => {
        if (account.address) fetch_NFTs();
        setNFTs(NFTs_queryResponse.data);
    }, [account.address]);

    console.log(NFTs_queryResponse);
    console.log(account.address);

    return (
        <div className={styles.container}>
            <Head>
                <title>RainbowKit App</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <div className={styles.connect}>
                <Web3Button />
            </div>

            <div>
                {account.address ? (
                    <>
                        <ConnectNft nftData={NFTs_queryResponse.data} />
                    </>
                ) : (
                    <Pooltogether />
                )}
            </div>
            <footer className={styles.footer}>
                <a
                    href="https://rainbow.me"
                    rel="noopener noreferrer"
                    target="_blank"
                >
                    Made with ❤️ by your frens at 🌈
                </a>
            </footer>
        </div>
    );
};

export default Home;
